board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('register/', views.register),
    path('login/', views.login),
    path('logout/', views.logout),
    path('list/', views.board_list),
    path('write/', views.board_write),
    path('detail/<int:pk>/', views.board_detail),
    path('detail/<int:pk>/update/', views.board_update),
    path('detail/<int:pk>/delete/', views.board_delete),
    path('guide/', views.guide),
    path('aboutus/', views.aboutus),
    path('design/', views.design),
    path('mypage/', views.mypage),
    path('mypage/update/', views.mypage_update)
]

community/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from board.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('', home),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models

# Create your models here.

class Member(models.Model):
    user_email      = models.EmailField(max_length=100, verbose_name='유저 이메일')
    user_pw         = models.CharField(max_length=100, verbose_name='유저 비밀번호')
    user_created    = models.DateTimeField(auto_now_add=True, verbose_name='가입일')
    user_updated    = models.DateTimeField(auto_now=True, verbose_name='수정일')

    def __str__(self):
        return self.user_email

    class Meta:
        db_table            = 'members'
        verbose_name        = '사용자'
        verbose_name_plural = '사용자'


class Board(models.Model):
    title       = models.CharField(max_length=200, verbose_name='제목')
    contents    = models.TextField(verbose_name='내용')
    writer      = models.ForeignKey('board.Member', on_delete=models.CASCADE, verbose_name='작성자')
    created_at  = models.DateTimeField(auto_now_add=True, verbose_name='작성일')
    updated_at  = models.DateTimeField(auto_now=True, verbose_name='수정일')
    image       = models.ImageField(upload_to='images/', blank=True, null=True)
    # pip install django-imagekit
    # image       = ProcessedImageField(
    #     blank=True, processors=[Thumbnail(300, 300),], format='JPEG', options={'quality':90,}
    # )

    def __str__(self):
        return self.title

    class Meta:
        db_table            = 'boards'
        verbose_name        = '게시판'
        verbose_name_plural = '게시판'


class UserCars(models.Model):
    user_email = models.ForeignKey('board.Member', on_delete=models.CASCADE, verbose_name='유저 이메일')
    user_design = models.ImageField(width_field=512, height_field=512, verbose_name='저장 디자인')
    saved_at = models.DateTimeField(auto_now_add=True, verbose_name='저장 시각')

    class Meta:
        db_table = 'usercars'
        verbose_name = '유저 저장 이미지'
        verbose_name_plural = '유저 저장 이미지'


class Cars(models.Model):
    type = models.CharField(max_length=20, verbose_name='차종')
    brand = models.CharField(max_length=20, verbose_name='브랜드')
    design = models.ImageField(width_field=512, height_field=512, verbose_name='디자인')

    class Meta:
        db_table = 'cars'
        verbose_name = '디자인데이터'
        verbose_name_plural = '디자인데이터'

board/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from .models import Member, Board

class LoginForm(forms.Form):
    user_email = forms.CharField(
        error_messages={'required' : '이메일을 입력하세요.'},
        max_length=100,
        label='사용자이름')
    user_pw = forms.CharField(
        error_messages={'required' : '비밀번호를 입력하세요.'},
        widget=forms.PasswordInput,
        max_length=100,
        label='비밀번호')

    def clean(self):
        cleaned_data = super().clean()
        user_email = cleaned_data.get('user_email')
        user_pw = cleaned_data.get('user_pw')

        if user_email and user_pw:
            # 입력한 이메일이 없을 경우 에외처리
            try:
                member = Member.objects.get(user_email=user_email)
            except Member.DoesNotExist:
                self.add_error('user_email', '아이디가 없습니다.')
                return
            
            if not check_password(user_pw, member.user_pw):
                self.add_error('user_pw', '비밀번호가 다릅니다.')
            else:
                self.user_id = member.id


class BoardForm(forms.Form):
    # 입력 받을 값
    title = forms.CharField(
        error_messages={'required': '제목을 입력하세요.'},
        max_length=100,
        label='게시글 제목')
    contents = forms.CharField(
        error_messages={'required': '내용을 입력하세요.'},
        widget=forms.Textarea,
        label='게시글 내용')
    image = forms.ImageField(
        label='첨부 이미지',
        widget=forms.ClearableFileInput,
        allow_empty_file=True
    )


class BoardUpdate(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'contents', 'image']

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Member, Board, Cars
from django.contrib.auth.hashers import make_password, check_password
from django.http import HttpResponse
from .forms import LoginForm, BoardForm, BoardUpdate
from django.http import Http404
from django.core.paginator import Paginator
from django.contrib import messages
from PIL import Image as pil
from io import BytesIO

# Create your views here.
def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    elif request.method == 'POST':
        user_email = request.POST.get('email')
        user_pw = request.POST.get('password')
        user_pw_confirm = request.POST.get('password-check')

        res_data = {}
        #모든 값을 입력하지 않았을 때
        if (user_email is None) or (user_pw is None) or (user_pw_confirm is None):
            res_data['error'] = '모든 값을 입력해야 합니다.'
            return render(request, 'register.html', res_data)
        #입력받은 비밀번호가 다를때
        elif user_pw != user_pw_confirm:
            res_data['error'] = '비밀번호가 다릅니다.'
            return render(request, 'register.html', res_data)
        #이미 등록된 이메일 주소일 경우
        elif Member.objects.filter(user_email=user_email).exists():
            res_data['error'] = '이미 등록된 이메일 주소입니다.'
            return render(request, 'register.html', res_data)
        else:
            #입력받은 사용자 정보를 객체를 만들어서 저장
            member = Member(
                user_email = user_email,
                #비밀번호 형태로 바꾸어서 저장
                user_pw = make_password(user_pw)
            )
            member.save()
        return redirect('/')
        # return render(request, 'register.html', res_data)


def mypage(request):
    user_id = request.session.get('user')
    if not user_id:
        return redirect('/board/login/')
    else:
        member = Member.objects.get(id=user_id)
        return render(request, 'mypage.html', {'member':member})

def mypage_update(request):
    return render(request, 'mypage_update.html')


def home(request):
    '''
    user_id = request.session.get('user')
    if user_id:
        member = Member.objects.get(pk=user_id)
        return HttpResponse(member.user_email)
    return HttpResponse('Home!')
    '''
    return render(request, 'home.html')

def guide(request):
    return render(request, 'guide.html')

def aboutus(request):
    return render(request, 'aboutus.html')

def design(request):
    if request.method == 'POST':
        type = request.POST.get('type')
        brand = request.POST.get('Brands')
        cat_type = ['Hatchback', 'Sedan', 'Sports car', 'SUV', 'Van']
        cat_brand = ['AUDI', 'Bentley', 'Benz', 'BMW', 'Chervolet', 'Chrysler',
                     'Ferrari', 'Ford', 'Hyundai', 'Kia', 'Lamborghini', 'Landrover',
                     'Mini', 'Nissan', 'Porsche', 'Ssangyong', 'Toyota', 'Volkswagen']
        res = Cars.objects.filter(type=type, brand=brand)

    return render(request, 'design.html')

def login(request):
    '''
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        user_email = request.POST.get('email')
        user_pw = request.POST.get('password')

        res_data = {}
        if not (user_email and user_pw):
            res_data['error'] = '모든 값을 입력하세요.'
        else:
            #데이터베이스에서 입력된 이메일의 사용자 정보를 가져온다.
            member = Member.objects.get(user_email=user_email)

            #비밀번호 검증
            if check_password(user_pw, member.user_pw):
                request.session['user'] = member.id
                return redirect('/')
            else:
                res_data['error'] = '비밀번호가 틀렸습니다.'
        return render(request, 'login.html', res_data)
        '''
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # session_code 검증
            request.session['user'] = form.user_id
            return redirect('/')
    else:
        form = LoginForm()
        # 빈 클래스 인스턴스 생성
    return render(request, 'login.html', {'form' : form})


def logout(request):
    if request.session.get('user'):
        del(request.session['user'])
    return redirect('/')


def board_list(request):
    all_boards = Board.objects.all().order_by('-id')
    page = int(request.GET.get('p', 1))
    #페이지 명을 'p'라는 변수로 받고 없다면 1페이지로
    pagenator = Paginator(all_boards, 5) #all_boards 의 내용을 한 페이지당 오브젝트 2개씩
    boards = pagenator.get_page(page)
    return render(request, 'board_list.html', {'boards' : boards})


def board_write(request):
    #로그인 하지 않은 접속자인지 확인
    if not request.session.get('user'):
        return redirect('/board/login/')

    if request.method == 'POST':
        form = BoardForm(request.POST, request.FILES)
        if form.is_valid():
            user_id = request.session.get('user')
            member = Member.objects.get(pk=user_id)

            board = Board()
            board.title = form.cleaned_data['title']
            board.contents = form.cleaned_data['contents']
            board.image = form.cleaned_data['image']
            #검증 성공 시 cleaned_data 제공
            #실패시 form.error에 오류 저장

            board.writer = member
            board.save()
            return redirect('/board/list/')
    else:
        form = BoardForm()
    return render(request, 'board_write.html', {'form' : form})


def rescale(image, width):
    img = pil.open(image)

    src_width, src_height = img.size
    if src_width <= width:
        return image
    else:
        src_ratio = float(src_height) / float(src_width)
        dst_height = round(src_ratio * width)

        img = img.resize((width, dst_height), pil.BILINEAR)
        # img.save(image.name, 'PNG')
        # image.file = img

        # 이게 없으면 attribute error 발생
        # image.file.name = image.name
        # return image
        return img


def board_detail(request, pk):
    try:
        board = Board.objects.get(pk=pk)
    except Board.DoesNotExist:
        raise Http404('게시글을 찾을 수 없습니다.')
    return render(request, 'board_detail.html', {'board':board})

def board_update(request, pk):
    user_id = request.session.get('user')
    #로그인하지 않았다면
    if not user_id:
        return redirect('/board/login/')

    # 기존의 작성글 객체를 찾는다.
    board = get_object_or_404(Board, id=pk)

    if board.writer.id != user_id:
        return redirect('/board/list/')
    else:
        if request.method == 'GET':
            form = BoardUpdate(instance=board)
            return render(request, 'board_update.html', {'form':form})

        elif request.method == 'POST':
            form = BoardUpdate(request.POST, request.FILES)
            if form.is_valid():
                user_id = request.session.get('user')
                member = Member.objects.get(pk=user_id)

                board = Board.objects.get(pk=pk)
                board.title = form.cleaned_data['title']
                board.contents = form.cleaned_data['contents']
                if form.cleaned_data['image']:
                    board.image = form.cleaned_data['image']
                else:
                    board.image = board.image
                # 검증 성공 시 cleaned_data 제공
                # 실패시 form.error에 오류 저장

                board.writer = member
                board.save()
                return redirect('/board/detail/' + str(pk))

        return render(request, 'board_update.html', {'form': form})


def board_delete(request, pk):
    if not request.session.get('user'):
        return redirect('/board/login/')
    board = Board.objects.get(pk=pk)
    board.delete()
    return redirect('/board/list/')

board/templates/aboutus.html
{% extends 'base.html' %} 

{% block content %} 
        <section class="review-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="titie-section wow fadeInDown animated ">
                            <h1>About us</h1>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div id="feedback" class="carousel slide feedback" data-ride="feedback">
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <div class="carousel-caption">
                                    <p> 서울특별시와 서울산업진흥원(SBA)의 혁신적 SW인재 양성기관 '싹'(SSAC, Seoul Software Academy Cluster)에서
                                    영상 처리를 위한 인공지능(머신러닝/AI) SW개발자 양성 과정을 수강한 3조 오파닭입니다.
                                    이는 저희의 2차 및 3차 프로젝트에 해당하는 결과물이며, 앞으로도 지속적인 업데이트와 발전을 위해 노력하겠습니다.
                                   </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="titie-section wow fadeInDown animated ">
                            <h1>멤버 소개</h1>
                        </div>
                    </div>
                </div>
                <div class="row">
                  <div id="feedback" class="carousel slide feedback" data-ride="feedback">
                    <div class="carousel-inner" role="listbox">
                        <div class="item active wow fadeInDown animated" data-wow-delay="0.3s">
                          <div class="method">
                            <img src="/static/images/member.png" width="1000" height="700" alt="">
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
            </div>
        </section>
{% endblock %} 

board/templates/base.html
<!doctype html>
<html class="no-js" lang="kor">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Show Car</title>
        <meta name="description" content="Design car">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="/static/css/style.css">

        <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <script>window.html5 || document.write('<script src="js/vendor/html5shiv.js"><\/script>')</script>
        <![endif]-->
        <script 
            src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"
        ></script>
    </head>
    <body>

        <!-- PRELOADER -->
        <div id="preloader">
            <div class="preloader-area">
            	<div class="preloader-box">
            		<div class="preloader"></div>
            	</div>
            </div>
        </div>

        <header class="header-section">
            <nav class="navbar navbar-default">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                    	<a class="navbar-brand" href="/"><b>H</b>ome</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right cart-menu">
                            <li><a href="/board/aboutus/">About Us</a></li>
                            <li><a href="/board/guide/">Guide</a></li>
                            <li><a href="/board/design/">Design</a></li>
                            <li><a href="/board/list/">Community</a></li>
        {% if request.session.user %}
                            <li><a href="/board/logout/">Logout</a></li>
        {% else %}
                            <li><a href="/board/login/">Login</a></li>
        {% endif %}
                            <li><a href="/board/mypage/"><span class="login">MY</span></a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container -->
            </nav>
        </header>
        {% block content %}
        {% endblock %}        
        <footer class="footer">
            <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="social-media">
                      <ul>
                        <li><a href="https://github.com/tyeong2/SSAC_project3"><i class="fa fa-github"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                      </ul>
                    </div>
                      <p class="center">Copyright 오파닭 All rights reserved. Developed by <i class="fa fa-love"></i><a href="https://ssac.seoul.kr/main/index.jsp">SSAC</a></p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- JQUERY -->
        <script src="/static/js/vendor/jquery-1.11.2.min.js"></script>
        <script src="/static/js/vendor/bootstrap.min.js"></script>
        <script src="/static/js/isotope.pkgd.min.js"></script>
        <script src="/static/js/owl.carousel.min.js"></script>
        <script src="/static/js/wow.min.js"></script>
        <script src="/static/js/custom.js"></script>
    </body>
</html>

board/templates/board_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <div class="form-group">
                <label for="title">제목</label>
                <!--input
                        type="text"
                        class="form-conrtrol"
                        id="title"
                        value="{{ board.title }}"
                        readonly
                / -->
                <textarea class="form-control" readonly>{{ board.title }}</textarea>
                <label for="contents">내용</label>
                <textarea class="form-control" readonly>{{ board.contents }}</textarea>
                <label for="image">디자인</label><br>
                {% if board.image %}
                <img src="{{ board.image.url }}" alt="{{ board.image }}" onerror="this.style.display='none';" readonly/>
                {% endif %}
            </div>
            {% if board.writer %}
            <button class="btn btn-primary" onclick="location.href='/board/detail/{{ board.id }}/update/'">수정하기</button>
            <a class="btn btn-primary" href="/board/detail/{{ board.id }}/delete/" onclick="return confirm('Are you sure you want to delete this?')"
            >삭제하기</a>
            {% endif %}
            <button class="btn btn-primary" onclick="location.href='/board/list/'">목록으로</button>
        </div>
    </div>
</div>
{% endblock %}

board/templates/board_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">제목</th>
                    <th scope="col">아이디</th>
                    <th scope="col">작성일</th>
                    <th scope="col">수정일</th>
                </tr>
                </thead>

                <tbody>
                {% for board in boards %}
                <tr onclick="location.href='/board/detail/{{ board.id }}/'">
                    <th scope="row">{{ board.id }}</th>
                    <td>{{ board.title }}</td>
                    <td>{{ board.writer }}</td>
                    <td>{{ board.created_at }}</td>
                    <td>{{ board.updated_at }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
        <!-- 여기에 부트스트랩 페이지네이션 코드 복붙 -->
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if boards.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?p={{ boards.previous_page_number }}">Previous</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Previous</a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="#">{{ boards.number }} / {{ boards.paginator.num_pages }}</a>
                    </li>
                    {% if boards.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?p={ boards.next_page_number }}">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <button type="button" class="btn btn-primary" onclick="location.href='/board/write/'">글쓰기</button>
        </div>
    </div>
</div>
{% endblock %}

board/templates/board_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">게시글 제목</label>
                    <input type="text" class="form-control" id="id_title" placeholder="게시글 제목" name="title" value="{{ form.title.value }}"/>
                </div>
                <div class="form-group">
                    <label for="id_contents">게시글 내용</label>
                    <textarea class="form-control" name="contents" placeholder="게시글 내용">{{ form.contents.value }}</textarea>
                </div>
                <div class="form-group">
                    <label for="id_image">첨부 이미지</label>
                    <input type="file" class="form-control" id="id_image" placeholder="첨부 이미지" name="image" value="{{ form.image.url }}"/>
                </div>
                <button type="submit" class="btn btn-primary">수정하기</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

board/templates/board_write.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% ifequal field.name 'contents' %}
                    <textarea
                        class="form-conrtrol"
                        name="{{ field.name }}"
                        placeholder="{{ field.label }}"
                    ></textarea>
                    {% else %}
                    <input
                            type="{{ field.field.widget.input_type }}"
                            class="form-conrtrol"
                            id="{{ field.id_for_label }}"
                            placeholder="{{ field.label }}"
                            name="{{ field.name }}"
                    />
                    {% endifequal %}
                </div>
                {% if field.errors %}
                <span style="color: red;">{{ field.errors }}</span>
                {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-primary">글쓰기</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

board/templates/home.html
{% extends 'base.html' %} 

{% block content %} 
    <section class="slider-section">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators slider-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="/static/images/sliderA.jpg" width="1648" height="600" alt="">
                <div class="carousel-caption">
                    <h2><b>S</b>how Car</h2>
                    <br>
                    <h3>자동차를 <Span>내 마음대로</Span> 디자인하다.</h3>
                    <a href="/board/design/">Start</a>
                </div>
            </div>
            <div class="item">
                <img src="/static/images/sliderB.jpg" width="1648" height="600" alt="">
                    <div class="carousel-caption">
                    <h2><b>S</b>how Car</h2>
                    <h3>자동차를 <Span>내 마음대로</Span> 디자인하다.</h3>
                    <a href="/board/design/">Start</a>
                    </div>
            </div>
                <div class="item">
                    <img src="/static/images/sliderC.jpg" width="1648" height="600" alt="">
                    <div class="carousel-caption">
                        <h2><b>S</b>how Car</h2>
                        <h3>자동차를 <Span>내 마음대로</Span> 디자인하다.</h3>
                        <a href="/board/design/">Start</a>
                    </div>
                </div>
                <div class="item ">
                    <img src="/static/images/sliderD.jpg" width="1648" height="600" alt="">
                    <div class="carousel-caption">
                        <h2><b>S</b>how Car</h2>
                        <h3>자동차를 <Span>내 마음대로</Span> 디자인하다.</h3>
                        <a href="/board/design/">Start</a>
                    </div>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="pe-7s-angle-left glyphicon-chevron-left" aria-hidden="true"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="pe-7s-angle-right glyphicon-chevron-right" aria-hidden="true"></span>
            </a>
        </div>
    </section>
{% endblock %} 

board/templates/intro.html
{% extends 'base.html' %} 

{% block content %} 
        <section class="review-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="titie-section wow fadeInDown animated ">
                            <h1>About us</h1>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div id="feedback" class="carousel slide feedback" data-ride="feedback">
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <div class="carousel-caption">
                                    <p> 서울특별시와 서울산업진흥원(SBA)의 혁신적 SW인재 양성기관 '싹'(SSAC, Seoul Software Academy Cluster)에서
                                    영상 처리를 위한 인공지능(머신러닝/AI) SW개발자 양성 과정을 수강한 3조 오파닭입니다.
                                    이는 저희의 2차 및 3차 프로젝트에 해당하는 결과물이며, 앞으로도 지속적인 업데이트와 발전을 위해 노력하겠습니다.
                                   </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="titie-section wow fadeInDown animated ">
                            <h1>멤버 소개</h1>
                        </div>
                    </div>
                </div>
                <div class="row">
                  <div id="feedback" class="carousel slide feedback" data-ride="feedback">
                    <div class="carousel-inner" role="listbox">
                        <div class="item active wow fadeInDown animated" data-wow-delay="0.3s">
                          <div class="method">
                            <img src="images/member.png" width="1000" height="700" alt="">
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
            </div>
        </section>
{% endblock %}

board/templates/mypage.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <div class="form-group">
                <label for="email">이메일</label>
                <textarea class="form-control" readonly>{{ member.user_email }}</textarea>
                <label for="created_at">가입일</label>
                <textarea class="form-control" readonly>{{ member.user_created }}</textarea>
                <label for="updated_at">수정일</label>
                <textarea class="form-control" readonly>{{ member.user_updated }}</textarea>
                <!-- 유저 저장 이미지 영역 -->
            </div>
        </div>
    </div>
</div>
{% endblock %}